#!/bin/ksh

# Wrapper to a bunch of archivers.

typeset -l SFX

whence gtar >/dev/null && TAR="gtar" || TAR="tar"

function die
{
	print "$1"
	exit ${1:-2}
}

function unpack_file
{
	# check a file and unpack it if we can
	# $1 is the file

	if ! test -s "$1"
	then
		print "ERROR: '$1' does not exist or is not a file"
		return 1
	fi

	SFX=${1##*.}

	case $SFX in
		"7z")
				ARC="7z x \"$1\""
				;;

		"bz2"|"tbz")
				ARC="bzip2 -dc \"$1\" | $TAR -xf -"
				;;

		"gz")	ARC="gzip -dc \"$1\" | $TAR -xf -"
				;;

		"tgz")	ARC="gzip -dc \"$1\" | $TAR -xf -"
				;;

		"z")	ARC="uncompress -c \"$1\"  | $TAR -xf -"
				;;

		"tar")	ARC="$TAR -xf \"$1\""
				;;

		"zip")	ARC="unzip -qq -o \"$1\""
				;;

		"jar")	ARC="jar -xf \"$1\""
				;;

		"rar")	ARC="unrar -y -inul e \"$1\""
				;;

		"xz")	ARC="xz -dc \"$1\" | $TAR -xf -"
				;;
	esac

	if [[ -n $ARC ]]
	then
		print -n "unpacking $1: "
		eval $ARC && print "ok" || print "FAILED"
	else
		print "ERROR: don't know what to do with '$1'"
	fi

}

function unpack_into_dir
{
	archive_file="$1"
	fname="${1##*/}"
	dir="${fname%.*}"
	print "Creating directory ${dir}"
	mkdir -p "$dir"
	cd "$dir"
	unpack_file "$archive_file"
	cd -
}

if [[ $1 == "-d" ]]
then
	MKDIR=true
	shift
fi

if (( $# == 0 ))
then
	print "usage: ${0##*/} <file>..."
	exit 1
fi

for file
do
	if [[ x$MKDIR == x ]]
	then
		unpack_file "$file"
	else
		unpack_into_dir "$file"
	fi
done
